//=============================================================================
// Original Coder - Common Library
//-----------------------------------------------------------------------------
// Visit the Original Coder Blog at http://OriginalCoder.dev
// Hosted at https://github.com/TheOriginalCoder/Original-Coder-Libraries
//-----------------------------------------------------------------------------
// Copyright (C) 2019 by James B. Higgins
// Released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3
//=============================================================================

using JetBrains.Annotations;
using OriginalCoder.Common.Interfaces.Properties;

namespace OriginalCoder.Common.Api
{
    /// <summary>
    /// Represents the results of an operation.
    /// </summary>
    [PublicAPI]
    public interface IOcApiResult : IName, ISummary
    {
        /// <summary>
        /// Returns true if there are no error messages.
        /// </summary>
        bool Success { get; }

        /// <summary>
        /// Collection of messages generated by the operation.
        /// </summary>
        [CanBeNull] IOcApiMessages Messages { get; }
    }

    /// <summary>
    /// Represents the results of an operation that returns data.
    /// </summary>
    /// <typeparam name="TData">Type of data that is returned.</typeparam>
    [PublicAPI]
    public interface IOcApiResult<out TData> : IOcApiResult
    {
        /// <summary>
        /// Data returned from the operation.
        /// </summary>
        TData Data { get; }
    }
}